{{- if and .Values.webhook.enabled (not .Values.webhook.externalSecretName) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "provider-postgresql.fullname" . }}-webhook-tls
  labels:
    {{- include "provider-postgresql.labels" . | nindent 4 }}
data:
  tls.crt: {{ .Values.webhook.certificate }}
  tls.key: {{ .Values.webhook.privateKey }}
{{- end -}}
