apiVersion: v1
kind: Service
metadata:
  name: {{ include "provider-postgresql.fullname" . }}
  labels:
    {{- include "provider-postgresql.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 443
      targetPort: webhook
      protocol: TCP
      name: webhook
  selector:
    {{- include "provider-postgresql.selectorLabels" . | nindent 4 }}
