{{- if .Values.webhook.enabled -}}
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: '{{ include "provider-postgresql.fullname" . }}'
  labels:
    {{- include "provider-postgresql.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.webhook.annotations | nindent 4 }}
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: '{{ include "provider-postgresql.fullname" . }}'
        namespace: '{{ .Release.Namespace }}'
        path: /mutate-postgresql-appcat-vshn-io-v1alpha1-postgresqlstandalone
{{- with .Values.webhook.caBundle }}
      caBundle: '{{ . }}'
{{- end }}
    failurePolicy: Fail
    name: postgresqlstandalones.postgresql.appcat.vshn.io
    rules:
      - apiGroups:
          - postgresql.appcat.vshn.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - postgresqlstandalones
    sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: '{{ include "provider-postgresql.fullname" . }}'
  labels:
    {{- include "provider-postgresql.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.webhook.annotations | nindent 4 }}
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: '{{ include "provider-postgresql.fullname" . }}'
        namespace: '{{ .Release.Namespace }}'
        path: /validate-postgresql-appcat-vshn-io-v1alpha1-postgresqlstandalone
{{- with .Values.webhook.caBundle }}
      caBundle: '{{ . }}'
{{- end }}
    failurePolicy: Fail
    name: postgresqlstandalones.postgresql.appcat.vshn.io
    rules:
      - apiGroups:
          - postgresql.appcat.vshn.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
          - DELETE
        resources:
          - postgresqlstandalones
    sideEffects: None
{{- end -}}
