apiVersion: postgresql.appcat.vshn.io/v1alpha1
kind: PostgresqlStandalone
metadata:
  name: my-instance
  namespace: default
spec:
  backup:
    enabled: true
  forInstance:
    enableSuperUser: true
    majorVersion: v14
    resources:
      memoryLimit: 256Mi
      storageCapacity: 1Gi
  writeConnectionSecretToRef: {}
