apiVersion: postgresql.appcat.vshn.io/v1alpha1
kind: PostgresqlStandalone
metadata:
  creationTimestamp: null
  generation: 1
  name: my-instance
  namespace: default
spec:
  backup:
    enabled: true
  forInstance:
    enableSuperUser: true
    majorVersion: v14
    resources:
      memoryLimit: 256Mi
      storageCapacity: 1Gi
  writeConnectionSecretToRef: {}
status:
  conditions:
  - lastTransitionTime: "2022-04-27T15:20:13Z"
    message: ""
    reason: Available
    status: "True"
    type: Ready
  deploymentStrategy: HelmChart
  helmChart:
    modifiedAt: "2022-04-27T15:20:13Z"
    name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 11.1.23
