//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresqlStandalone) DeepCopyInto(out *PostgresqlStandalone) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresqlStandalone.
func (in *PostgresqlStandalone) DeepCopy() *PostgresqlStandalone {
	if in == nil {
		return nil
	}
	out := new(PostgresqlStandalone)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PostgresqlStandalone) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresqlStandaloneList) DeepCopyInto(out *PostgresqlStandaloneList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PostgresqlStandalone, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresqlStandaloneList.
func (in *PostgresqlStandaloneList) DeepCopy() *PostgresqlStandaloneList {
	if in == nil {
		return nil
	}
	out := new(PostgresqlStandaloneList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PostgresqlStandaloneList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresqlStandaloneObservation) DeepCopyInto(out *PostgresqlStandaloneObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresqlStandaloneObservation.
func (in *PostgresqlStandaloneObservation) DeepCopy() *PostgresqlStandaloneObservation {
	if in == nil {
		return nil
	}
	out := new(PostgresqlStandaloneObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresqlStandaloneParameters) DeepCopyInto(out *PostgresqlStandaloneParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresqlStandaloneParameters.
func (in *PostgresqlStandaloneParameters) DeepCopy() *PostgresqlStandaloneParameters {
	if in == nil {
		return nil
	}
	out := new(PostgresqlStandaloneParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresqlStandaloneSpec) DeepCopyInto(out *PostgresqlStandaloneSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	out.ForProvider = in.ForProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresqlStandaloneSpec.
func (in *PostgresqlStandaloneSpec) DeepCopy() *PostgresqlStandaloneSpec {
	if in == nil {
		return nil
	}
	out := new(PostgresqlStandaloneSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresqlStandaloneStatus) DeepCopyInto(out *PostgresqlStandaloneStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresqlStandaloneStatus.
func (in *PostgresqlStandaloneStatus) DeepCopy() *PostgresqlStandaloneStatus {
	if in == nil {
		return nil
	}
	out := new(PostgresqlStandaloneStatus)
	in.DeepCopyInto(out)
	return out
}
