apiVersion: postgresql.appcat.vshn.io/v1alpha1
kind: PostgresqlStandalone
metadata:
  creationTimestamp: null
  generation: 1
  name: standalone
spec:
  backup:
    enabled: false
  monitoring:
    sla: BestEffort
  resources:
    memoryLimit: 2Gi
    size: 8Gi
  updatePolicy:
    maintenanceWindow:
      start: {}
    version:
      major: ""
status: {}
