apiVersion: postgresql.appcat.vshn.io/v1alpha1
kind: PostgresqlStandalone
metadata:
  creationTimestamp: null
  generation: 1
  name: standalone
spec:
  resources:
    memoryLimit: 2Gi
    size: 8Gi
status:
  conditions:
  - lastTransitionTime: "2022-04-27T13:21:46Z"
    message: ""
    reason: The resource is ready
    status: "True"
    type: Ready
  deploymentStrategy: HelmChart
  helmChart:
    modifiedAt: "2022-04-27T15:20:13Z"
    name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 11.1.23
