---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crossplane:provider:provider-helm:deployer
rules:
  - verbs:
      - '*'
    apiGroups:
      - ''
      - apps
      - batch
      - networking.k8s.io
      - helm.crossplane.io
    resources:
      - '*'
  - verbs:
      - '*'
    apiGroups:
      - rbac.authorization.k8s.io/v1
    resources:
      - roles
      - rolebindings
      - serviceaccounts
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: provider-helm
  namespace: crossplane-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crossplane:provider:provider-helm:deployer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crossplane:provider:provider-helm:deployer
subjects:
- kind: ServiceAccount
  name: provider-helm
  namespace: crossplane-system
