name: ChartsRelease

on:
  push:
    branches:
      - master
    paths:
      - 'charts/**'
      - '!charts/charts.mk'
      - '!charts/go*'

jobs:
  # Currently this job with changelog generator only works for the provider-postgresql chart...
  # More charts (e.g. forks) may need additional engineering to get the changelog right.
  gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Get chart versions
        run: |
          echo "CHART_VERSION=$(yq e '.version' charts/provider-postgresql/Chart.yaml)" >> $GITHUB_ENV
          echo "PREVIOUS_CHART_VERSION=$(git show HEAD^:charts/provider-postgresql/Chart.yaml -m | grep "version:" | cut -d ' ' -f 2)" >> $GITHUB_ENV

      - name: Prepare changelog config
        run: .github/changelog-charts.sh provider-postgresql

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.4.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Build changelog from PRs with labels
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v2
        with:
          configuration: ".github/configuration.json"
          # PreReleases still get a changelog, but the next full release gets a diff since the last full release,
          # combining possible changelogs of all previous PreReleases in between.
          # PreReleases show a partial changelog since last PreRelease.
          ignorePreReleases: "${{ !contains(env.CHART_VERSION, '-rc') }}"
          outputFile: charts/provider-postgresql/CHANGELOG.md
          fromTag: provider-postgresql-${{ env.PREVIOUS_CHART_VERSION }}
          toTag: provider-postgresql-${{ env.CHART_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # there doesn't seem to be any maintained GitHub actions that allow uploading assets after release has been made.
      - name: Update release
        run: |
          gh release upload provider-postgresql-${{ env.CHART_VERSION }} charts/provider-postgresql/crds.yaml
          gh release edit   provider-postgresql-${{ env.CHART_VERSION }} --notes-file charts/provider-postgresql/CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
