name: ChartLint

on:
  pull_request:
    # only run when there are chart changes
    paths:
      - 'charts/**'
      - '!charts/charts.mk'
      - '!charts/go*'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Verify charts are upt-do-date
        run: make chart-lint
